apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  labels:
    app: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - image: tomir/quotes:1.1
          name: quotes
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: quotes-postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quotes-postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: quotes-postgres-config
                  key: postgres_db
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: quotes-hostname-config
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: quotes-postgres-config
                  key: postgres_port
            - name: SPRING_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: quotes-postgres-config
                  key: spring_profile
